apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: research
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: frontend
        image: frontend
        command: [ "http-server", "dist"]
        ports:
        - containerPort: 8080